#!/bin/bash
if [ ! -f "$OPENSHIFT_DATA_DIR"secrets.json ]; then
	echo "Generating $OPENSHIFT_DATA_DIR/secrets.json"
	python3 "$OPENSHIFT_REPO_DIR"libs/secrets.py > "$OPENSHIFT_DATA_DIR"secrets.json
fi
